GD-12: propagate errors if test run fails (#13)

diff --git a/.github/workflows/ci-pr.yml b/.github/workflows/ci-pr.yml
--- a/.github/workflows/ci-pr.yml
+++ b/.github/workflows/ci-pr.yml
@@ -23,7 +23,7 @@ jobs:
       fail-fast: false
       max-parallel: 10
       matrix:
-        godot-version: ['4.1', '4.1.1', '4.1.2', '4.1.3', '4.2', '4.2.1']
+        godot-version: ['4.1.3', '4.2', '4.2.1']
         godot-status: ['stable']
         godot-net: ['', '.Net']
         version: ['master', 'latest', 'v4.2.0']
@@ -78,11 +78,51 @@ jobs:
           report-name: report_gdUnit4-${{ matrix.version }}_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}-net.xml
 
 
+  # tests if the action reports test failures the action must fail
+  action-fail-test:
+    runs-on: ubuntu-22.04
+    strategy:
+      fail-fast: false
+
+    name: 'GdUnit4 action fail test'
+
+    steps:
+      - name: 'Checkout gdUnit4-action'
+        uses: actions/checkout@v4
+        with:
+          lfs: true
+
+      - name: 'Install test project'
+        shell: bash
+        run: |
+          mv -f .github/workflows/resources/* .
+
+      - name: 'Run failing failing test'
+        id: test-fails
+        continue-on-error: true
+        timeout-minutes: 3
+        env:
+          GDUNIT_FAIL: 'true'
+        uses: ./
+        with:
+          godot-version: 4.2.1
+          paths: |
+            res://tests/
+          timeout: 2
+          report-name: report_action_fail_gdUnit4.xml
+
+      - if: ${{ steps.test-fails.outcome != 'failure' }}
+        shell: bash
+        run: |
+          echo "The step 'steps.test-fails' must fail but is ${{ steps.test-fails.outcome}}"
+          exit 1
+          
+
   finalize:
     if: ${{ !cancelled() }}
     runs-on: ubuntu-latest
     name: 'Final Results'
-    needs: [unit-tests]
+    needs: [unit-tests, action-fail-test]
     steps:
       - run: exit 1
         if: >-
